version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: boiler_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/www:/app/www
      - ./frontend/test:/app/test