version: '2'
services:
  mongo:
    image: mongo
    container_name: boiler_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.boilerstack/mongo:/data/db
  router:
    build:
      context: ./router
    container_name: boiler_router
    ports:
      - "80:80"
    links:
      - frontend:frontend
      - auth:auth
    external_links:
      - boiler_api:api
    environment:
      AUTH_SERVICE_HOST: auth
      AUTH_SERVICE_PORT: 80
      API_SERVICE_HOST: api
      API_SERVICE_PORT: 80
      FRONTEND_SERVICE_HOST: frontend
      FRONTEND_SERVICE_PORT: 80
  auth:
    image: binocarlos/passport-service
    container_name: boiler_auth
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      MONGO_SERVICE_HOST: mongo
      HOSTNAME: localhost
  digger:
    image: binocarlos/digger-rest
    container_name: boiler_digger
    volumes:
      - ./.boilerstack/digger:/data/db
  frontend:
    build:
      context: ./frontend
    container_name: boiler_frontend
    volumes:
      - ./frontend/dist:/app/www
  #api:
  #  build:
  #    context: ./api
  #  container_name: boiler_api
  #  links:
  #    - auth:auth
  #    - digger:digger
  #    - storage:storage
  #  volumes:
  #    - ./api/src:/app/src
  #  environment:
  #    AUTH_SERVICE_HOST: auth
  #    AUTH_SERVICE_PORT: 80
  #    DIGGER_SERVICE_HOST: digger
  #    DIGGER_SERVICE_PORT: 80
  #    STORAGE_SERVICE_HOST: storage
  #    STORAGE_SERVICE_PORT: 80
  storage:
    build:
      context: ./storage
    container_name: boiler_storage
    links:
      - mongo:mongo      
    volumes:
      - ./storage/src:/storage/src
    environment:
      MONGO_SERVICE_HOST: mongo
      MONGO_SERVICE_PORT: 27017
      MONGO_SERVICE_DATABASE: boilerstorge