version: '2'
services:
  frontendbuild:
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    container_name: boiler_frontend_build
    volumes:
      - ./frontend/dist:/app/dist
      - ./frontend/src:/app/src
      - ./frontend/www:/app/www