version: '2'
services:
  mongo:
    image: mongo
    container_name: boiler_mongo
    volumes:
      - ./.boilerstack/mongo:/data/db
  router:
    build:
      context: ./router
    container_name: boiler_router
    ports:
      - "80:80"
    links:
      - frontend:frontend
      - auth:auth
      - api:api
    environment:
      AUTH_SERVICE_HOST: auth
      AUTH_SERVICE_PORT: 80
      API_SERVICE_HOST: api
      API_SERVICE_PORT: 80
      FRONTEND_SERVICE_HOST: frontend
      FRONTEND_SERVICE_PORT: 80
  auth:
    image: binocarlos/passport-service
    container_name: boiler_auth
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      - MONGO_SERVICE_HOST=mongo
      - HOSTNAME=localhost
  digger:
    image: binocarlos/digger-rest
    container_name: boiler_digger
    volumes:
      - ./.boilerstack/digger:/data/db
  api:
    build:
      context: ./api
    links:
      - auth:auth
      - digger:digger
    volumes:
      - ./api/src:/app/src
      - ./api/node_modules:/app/node_modules
    environment:
      AUTH_SERVICE_HOST: auth
      AUTH_SERVICE_PORT: 80
      DIGGER_SERVICE_HOST: digger
      DIGGER_SERVICE_PORT: 80
  frontend:
    build:
      context: ./frontend
    container_name: boiler_frontend
    volumes:
      - ./frontend/dist:/app/www