version: '2'
services:
  redis:
    image: redis
    container_name: boiler_redis
    environment:
      LOGSPOUT: ignore
    volumes:
      - ./.data/redis:/data
  postgres:
    image: postgres:9.6.1
    container_name: boiler_postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: boiler
      POSTGRES_PASSWORD: boiler
      POSTGRES_DB: boiler
      LOGSPOUT: ignore
  router:
    image: binocarlos/noxy
    container_name: boiler_router
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
    links:
      - frontend:frontend
      - api:api
    environment:
      NOXY_API_FRONT: /api/v1
      NOXY_API_HOST: api
      NOXY_DEFAULT_HOST: frontend
      LOGSPOUT: ignore
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: boilerstack_frontend_dev
    container_name: boilerstack_frontend_dev
    environment:
      LOGSPOUT: ignore
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/www:/app/www
      - ./frontend/test:/app/test
      - ./frontend/dist:/app/dist
  api:
    build:
      context: ./api
    # will reload the app on file change
    container_name: boiler_api
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./api/src:/app/src
    entrypoint:
      - "sleep"
      - "10000000"
    environment:
      NODE_ENV: development
      LOGLEVEL: trace
      DIGGER_SERVICE_HOST: digger
      DIGGER_SERVICE_PORT: 80
      REDIS_SERVICE_HOST: redis
      REDIS_SERVICE_PORT: 6379
      POSTGRES_SERVICE_HOST: postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_SERVICE_USER: boiler
      POSTGRES_SERVICE_PASSWORD: boiler
      POSTGRES_SERVICE_DATABASE: boiler
