version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: boilerstack_frontend_dev
    container_name: boilerstack_frontend_dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/www:/app/www
      - ./frontend/test:/app/test
      - ./frontend/dist:/app/dist
  frontend_cli:
    extends: 
      file: docker-compose.dev.yml
      service: frontend
    links:
      - router:router