version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: boilerstack_frontend_prod
    container_name: boilerstack_frontend_prod
    ports:
      - "8888:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html